/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type CreateProfileDataStruct = {
  to: string;
  handle: string;
  imageURI: string;
  followModule: string;
  followModuleData: BytesLike;
  followNFTURI: string;
};

export type CreateProfileDataStructOutput = [
  string,
  string,
  string,
  string,
  string,
  string
] & {
  to: string;
  handle: string;
  imageURI: string;
  followModule: string;
  followModuleData: string;
  followNFTURI: string;
};

export type PostDataStruct = {
  profileId: BigNumberish;
  contentURI: string;
  collectModule: string;
  collectModuleData: BytesLike;
  referenceModule: string;
  referenceModuleData: BytesLike;
};

export type PostDataStructOutput = [
  BigNumber,
  string,
  string,
  string,
  string,
  string
] & {
  profileId: BigNumber;
  contentURI: string;
  collectModule: string;
  collectModuleData: string;
  referenceModule: string;
  referenceModuleData: string;
};

export interface PeoplesChannelInterface extends utils.Interface {
  functions: {
    "createChannel((address,string,string,address,bytes,string))": FunctionFragment;
    "createPost((uint256,string,address,bytes,address,bytes))": FunctionFragment;
    "getHandlesByOwner(address)": FunctionFragment;
    "isAllowed(address)": FunctionFragment;
    "isCreator(address)": FunctionFragment;
    "ownerToHandles(address,uint256)": FunctionFragment;
    "postsByChannel(string,uint256)": FunctionFragment;
    "setFollowModule(uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createChannel",
    values: [CreateProfileDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [PostDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getHandlesByOwner",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isAllowed", values: [string]): string;
  encodeFunctionData(functionFragment: "isCreator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "ownerToHandles",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postsByChannel",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFollowModule",
    values: [BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHandlesByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCreator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerToHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postsByChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFollowModule",
    data: BytesLike
  ): Result;

  events: {
    "newChannel(address,string)": EventFragment;
    "newChannelPost(address,string,string,address,bytes,address,bytes,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "newChannel"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "newChannelPost"): EventFragment;
}

export type newChannelEvent = TypedEvent<
  [string, string],
  { creator: string; channelName: string }
>;

export type newChannelEventFilter = TypedEventFilter<newChannelEvent>;

export type newChannelPostEvent = TypedEvent<
  [string, string, string, string, string, string, string, BigNumber],
  {
    creator: string;
    channelName: string;
    contenURI: string;
    collectModule: string;
    collectModuleReturnData: string;
    referenceModule: string;
    referenceModuleReturnData: string;
    timestamp: BigNumber;
  }
>;

export type newChannelPostEventFilter = TypedEventFilter<newChannelPostEvent>;

export interface PeoplesChannel extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PeoplesChannelInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createChannel(
      vars: CreateProfileDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createPost(
      vars: PostDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getHandlesByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    isAllowed(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isCreator(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    ownerToHandles(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    postsByChannel(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setFollowModule(
      profileId: BigNumberish,
      followModule: string,
      followModuleData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createChannel(
    vars: CreateProfileDataStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createPost(
    vars: PostDataStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getHandlesByOwner(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  isAllowed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isCreator(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  ownerToHandles(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  postsByChannel(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setFollowModule(
    profileId: BigNumberish,
    followModule: string,
    followModuleData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createChannel(
      vars: CreateProfileDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createPost(vars: PostDataStruct, overrides?: CallOverrides): Promise<void>;

    getHandlesByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    isAllowed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isCreator(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    ownerToHandles(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    postsByChannel(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setFollowModule(
      profileId: BigNumberish,
      followModule: string,
      followModuleData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "newChannel(address,string)"(
      creator?: string | null,
      channelName?: string | null
    ): newChannelEventFilter;
    newChannel(
      creator?: string | null,
      channelName?: string | null
    ): newChannelEventFilter;

    "newChannelPost(address,string,string,address,bytes,address,bytes,uint256)"(
      creator?: string | null,
      channelName?: string | null,
      contenURI?: null,
      collectModule?: null,
      collectModuleReturnData?: null,
      referenceModule?: null,
      referenceModuleReturnData?: null,
      timestamp?: BigNumberish | null
    ): newChannelPostEventFilter;
    newChannelPost(
      creator?: string | null,
      channelName?: string | null,
      contenURI?: null,
      collectModule?: null,
      collectModuleReturnData?: null,
      referenceModule?: null,
      referenceModuleReturnData?: null,
      timestamp?: BigNumberish | null
    ): newChannelPostEventFilter;
  };

  estimateGas: {
    createChannel(
      vars: CreateProfileDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createPost(
      vars: PostDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getHandlesByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAllowed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isCreator(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    ownerToHandles(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    postsByChannel(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFollowModule(
      profileId: BigNumberish,
      followModule: string,
      followModuleData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createChannel(
      vars: CreateProfileDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createPost(
      vars: PostDataStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getHandlesByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAllowed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCreator(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerToHandles(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    postsByChannel(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFollowModule(
      profileId: BigNumberish,
      followModule: string,
      followModuleData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
